version: '3.1'

services:

  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
   container_name: elasticsearch
   ports:
    - "9200:9200"
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   networks:
    - docker-network
   environment:
    - discovery.type=single-node

  
  kibana:
   image: docker.elastic.co/kibana/kibana:7.5.1
   container_name: kibana
   ports:
    - "5601:5601"
   depends_on:
    - elasticsearch
   networks:
    - docker-network

  todoapi:
   image: todoapi:1.0
   container_name: todoapi
   ports:
    - "5000:80"
   networks:
    - docker-network
networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data: